### ISSUE TITLE
Filter ordering woes

### ISSUE THREAD

**Issue by ghost** [backdrop-contrib/invisimail#1]
This module doesn't seem to be working for me.

If I order the Javascript Invisimail filter before the Convert URLs to Links filter, it outputs a weird URL that doesn't work.

If I order the Javascript Invisimail filter after the Convert URLs to Links filter, it has no effect at all (this would be a nice feature, to enable obfuscating email addresses that are already mailto links).

**Comment by Graham-72** [comment]
@BWPanda thanks for reporting this. I will try and take a look soon. Any ideas are very welcome.

**Comment by ghost** [comment]
Ok, so I think I worked out that this is caused by an incompatibility between Invisimail and Pathologic. Well, they *can* work together, but that requires Pathologic to be run before Invisimail, and since Pathologic is supposed to be run last, and Invisimail first, then I'm not sure that's a good idea...

Not sure what to do there, but this doesn't seem to be a bug with Invisimail at least.

**Comment by ghost** [comment]
> ...since Pathologic is supposed to be run last, and Invisimail first, then I'm not sure that's a good idea...

I'm not sure where I got the idea that Invisimail is supposed to be run first...

Still having problems with this, I researched and eventually discovered that Invisimail doesn't work if run before the 'Correct faulty and chopped off HTML' filter (that just undoes the encoding performed by Invisimail if so). Therefore it seems that Invisimail should be one of the last filters to run (certainly after 'Correct faulty and chopped off HTML' and possibly also 'Pathologic').

Could we update the README/documentation to reflect this and avoid future issues with wrong ordering of filters?

**Comment by ghost** [comment]
I've made a PR for this (updated the README file). Along with updating the install docs, I also made a few other formatting/wording changes to adhere more to Backdrop standards (e.g. 80-char line length). Hope that's ok. If not, I can submit a new PR with just the change for this issue specifically.
