### ISSUE TITLE
Resolved: How to make invisimail work on items in blocks like the hero block

### ISSUE THREAD

**Issue by izmeez** [backdrop-contrib/invisimail#6]
How can invisimail be configured to work on mail addresses in blocks like the hero block?

**Comment by olafgrabienski** [comment]
If I recall correctly, the Hero block uses the Basic text format for the block content. If you didn't change the format, I'd suggest to add one of the "Encode email addresses" filters to that format.

**Comment by izmeez** [comment]
@olafgrabienski Thank you. Your reply got me to look at this further with the expectation it should work and I discovered it does work. My issue was that because the [extlink](https://backdropcms.org/project/extlink) module is also enabled on the site, it was necessary to move the "Convert URLs into links" filter to below the encode filter.

**Comment by izmeez** [comment]
I will close this issue.
